server:
  port: 8082

spring:
  application:
    name: msprodutos
  datasource:
    url: jdbc:postgresql://localhost:5433/products_db
    username: user2
    password: password2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    stream:
      function:
        definition: clienteToProdutoEventListener
      bindings:
        clienteToProdutoEventListener-in-0:
          destination: app.v1.event.cliente-to-produto
          group: produto
        produtoToEntregaSupplier-out-0:
          destination: app.v1.event.produto-to-entrega