server:
  port: 8081

spring:
  application:
    name: msclientes
  datasource:
    url: jdbc:postgresql://localhost:5432/clients_db
    username: user1
    password: password1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672


  cloud:
    stream:
      function:
        definition: pedidoCreatedEventListener
      bindings:
        pedidoCreatedEventListener-in-0:
          destination: app.v1.event.pedido-to-cliente
          group: cliente
        clienteToProdutoSupplier-out-0:
          destination: app.v1.event.cliente-to-produto

